<?php
namespace App\Helpers;
use DB;
use Mail;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use App\Models\User;
use App\Models\Blog;
use App\Models\Widget;
use App\Models\Testimonial;
use App\Models\Category;
use App\Models\CustomField;
use App\Models\CustomFieldValue;
use App\Models\Cms;
use App\Models\Menu;
use App\Models\MenuItem;
use App\Models\ServiceLevel;
use App\Models\Setting;
use App\Libraries\MobileDetect;
use App\Libraries\CurrencyConverter;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Cache;

use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Log;
use Illuminate\Http\Request;
use Intervention\Image\Laravel\Facades\Image;
use File;

class CustomHelper {
    /**
     * Render S3 image URL
     *
     * @param $name
     * @param bool $thumbnail
     * @return string
     */
    public static function getAdminRouteName() {
        $ADMIN_ROUTE_NAME = config("custom.ADMIN_ROUTE_NAME");
        if (empty($ADMIN_ROUTE_NAME)) {
            $ADMIN_ROUTE_NAME = "admin";
        }
        return $ADMIN_ROUTE_NAME;
    }

    /**
     * reCAPTCHA v3 Server-Side Verification Helper
     * 
     * This method verifies reCAPTCHA v3 tokens received from the frontend.
     * reCAPTCHA v3 provides a score (0.0-1.0) indicating how likely the user is human.
     * 
     * @param string $token The reCAPTCHA token from frontend (g-recaptcha-response)
     * @return array Google's verification response containing:
     *               - success: boolean (true if verification passed)
     *               - score: float (0.0 = bot, 1.0 = human)
     *               - action: string (action name from frontend)
     *               - challenge_ts: timestamp of challenge
     *               - hostname: domain where challenge was solved
     *               - error-codes: array (if verification failed)
     */
    public static function checkGoogleReCaptcha($token){
        // Retrieve reCAPTCHA secret key from application settings
        // This key should be stored securely in .env file and never exposed to frontend
        $websiteSettingsArr = self::getSettings('RECAPTCHA_SECRET_KEY');

        // Initialize cURL session for HTTP request to Google's verification endpoint
        $ch = curl_init();
        
        // Configure cURL options for reCAPTCHA verification
        curl_setopt($ch, CURLOPT_URL, "https://www.google.com/recaptcha/api/siteverify"); // Google's verification endpoint
        curl_setopt($ch, CURLOPT_POST, 1); // Use POST method (required by Google)
        
        // Prepare POST data with secret key and user's token
        // secret: Your private key from Google reCAPTCHA console
        // response: The token generated by grecaptcha.execute() on frontend
        curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query(array(
            'secret' => $websiteSettingsArr['RECAPTCHA_SECRET_KEY'],
            'response' => $token
        )));
        
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); // Return response as string instead of outputting
        
        // Execute the request and get Google's response
        $response = curl_exec($ch);
        curl_close($ch); // Clean up cURL session
       
        // Parse Google's JSON response into PHP array
        // Response format: {"success": true/false, "score": 0.0-1.0, "action": "action_name", ...}
        $arrResponse = json_decode($response, true);
        
        // Debug: Uncomment to inspect Google's full response during development
        // prd($arrResponse);

        // Return the complete response array for further processing
        // Calling code should check $response['success'] and optionally $response['score']
        // Typical score threshold: 0.5 (adjust based on your security requirements)
        return $arrResponse;
    }

    // Add getPrice For CurrencyConverter
    public static function getPrice($price = 0){
        $currencySymbol = '$';
        return $currencySymbol.(int)$price;
    }
    
    public static function currencySymbol($code = '')
    {
        $map = [
            'INR' => '₹',
            'USD' => '$',
            'EUR' => '€',
            'GBP' => '£',
            'AED' => 'د.إ',
        ];
        $code = strtoupper((string)$code);
        return $map[$code] ?? '$';
    }
    
    public static function formatCurrency($amount = 0, $code = 'USD', $withCode = true, $decimals = 0)
    {
        $sym = self::currencySymbol($code);
        $num = number_format((float)$amount, $decimals);
        if ($withCode) {
            return strtoupper((string)$code) . ' ' . $num;
        }
        return $sym . ' ' . $num;
    }

    public static function getTemplates($folder_path = "") {
        $result = [];
        $path = "";
        $exists = file_exists(base_path() . "/resources/views/front/templates/" . $folder_path);
        if ($exists) {
            $path = base_path("/resources/views/front/templates/") . $folder_path;
        } else {
            //$path='';
            
        }
        if (is_dir($path)) {
            if ($dh = opendir($path)) {
                while (($file = readdir($dh)) !== false) {
                    if (strlen($file) > 3) {
                        $expoldes = explode(".", $file);
                        $dir = $folder_path . "." . $expoldes[0];
                        $name = $expoldes[0];
                        $name = preg_replace('/[^A-Za-z0-9\-\']/', " ", $name);
                        $result[$dir] = ucfirst($name);
                    }
                }
                closedir($dh);
            }
        }
        return $result;
    }

    /**
     * Format a 10-digit phone number from xxxxxxxxxx to (xxx) xxx-xxxx
     *
     * @param $phone
     * @return string
     */
    public static function formatPhoneNumber($phone) {
        return strlen($phone) == 10 ? "(" . substr($phone, 0, 3) . ") " . substr($phone, 3, 3) . "-" . substr($phone, 6) : $phone;
    }

    public static function GetSlugBySelf($slug_array, $text) {
        $slug = "";
        // echo $text; die;
        // replace non letter or digits by -
        $text = preg_replace("~[^\pL\d]+~u", "-", $text);
        // transliterate
        $text = iconv("utf-8", "us-ascii//TRANSLIT", $text);
        // remove unwanted characters
        $text = preg_replace("~[^-\w]+~", "", $text);
        // trim
        $text = trim($text, "-");
        // remove duplicate -
        $text = preg_replace("~-+~", "-", $text);
        // lowercase
        $text = strtolower($text);
        // echo $text; die;
        if (empty($text)) {
            // return 'n-a';
            
        }
        $slug = self::GetUniqueSlugBySelf($slug_array, $text);
        // echo $slug; die;
        return $slug;
    }

    public static function GetUniqueSlugBySelf($slug_array, $slug = "", &$num = "") {
        $new_slug = $slug . $num;
        //pr($new_slug);
        $slug = $new_slug;
        if (is_array($slug_array) && in_array($slug, $slug_array)) {
            $num = (int)$num + 1;
            $slug = self::GetUniqueSlugBySelf($slug_array, $new_slug, $num);
        }
        return $slug;
    }

    public static function GetSlug($tbl_name, $id_field, $row_id = "", $text = "") {
        // echo $text; die;
        // replace non letter or digits by -
        $text = preg_replace("~[^\pL\d]+~u", "-", $text);
        // transliterate
        $text = iconv("utf-8", "us-ascii//TRANSLIT", $text);
        // remove unwanted characters
        $text = preg_replace("~[^-\w]+~", "", $text);
        // trim
        $text = trim($text, "-");
        // remove duplicate -
        $text = preg_replace("~-+~", "-", $text);
        // lowercase
        $text = strtolower($text);
        // echo $text; die;
        if (empty($text)) {
            // return 'n-a';
            
        }
        // echo $text; die;
        $slug = self::GetUniqueSlug($tbl_name, $id_field, $row_id, $text);
        // echo $slug; die;
        return $slug;
    }

    public static function GetUniqueSlug($tbl_name, $id_field, $row_id = "", $slug = "", &$num = "") {
        $new_slug = $slug . $num;
        $query = DB::table($tbl_name);
        $query->where("slug", $new_slug);
        $row = $query->first();
        if (empty($row)) {
            $slug = $new_slug;
        } else {
            if (!empty($row_id) && $row->$id_field == $row_id) {
                $slug = $new_slug;
            } else {
                $num = (int)$num + 1;
                $slug = self::GetUniqueSlug($tbl_name, $id_field, $row_id, $new_slug, $num);
            }
        }
        return $slug;
    }

    public static function getStatusStr($status) {
        if (is_numeric($status) && strlen($status) > 0) {
            if ($status == 1) {
                $status = "Active";
            } else {
                $status = "Inactive";
            }
        }
        return $status;
    }

    public static function getStatusHTML($status, $tbl_id = 0, $class = "", $id = "", $type = "status", $activeTxt = "Active", $inActiveTxt = "In-active") {
        $status_str = "";
        if (is_numeric($status) && strlen($status) > 0) {
            $status_name = "";
            $a_label = "";
            if ($status == 1) {
                $status_name = $activeTxt;
                $a_label = "label-success";
            } else {
                $status_name = $inActiveTxt;
                $a_label = "label-warning";
            }
            $status_str = '<a href="javascript:void(0)" class="label ' . $a_label . " " . $class . '" id="' . $id . '" data-id="' . $tbl_id . '" data-status="' . $status . '" data-type="' . $type . '" >' . $status_name . "</a>";
        }
        if (empty($status_str)) {
            $status_str = $status;
        }
        return $status_str;
    }

    public static function CheckAndFormatDate($date, $toFormat = "Y-m-d H:i:s", $fromFormat = "") {
        $new_date = $date;
        $date = preg_replace(["/\//", "/\./"], "-", $date);
        //echo $date; die;
        $new_date = self::DateFormat($date, $toFormat, $fromFormat = "y-m-d");
        return $new_date;
    }

    public static function DateFormat($date, $toFormat = "Y-m-d H:i:s", $fromFormat = "") {
        $new_date = $date;
        $formatArr = ["d-m-y", "d-m-Y", "d/m/Y", "d/m/y", "d/m/Y H:i:s", "d/m/y H:i:s", "d/m/Y H:i A", "d/m/y H:i A", ];
        if (empty($toFormat)) {
            $toFormat = "Y-m-d H:i:s";
        }
        if ($date != "0000-00-00 00:00:00" && $date != "0000-00-00" && $date != "") {
            if (empty($fromFormat) || $fromFormat == "" || !in_array($fromFormat, $formatArr)) {
                $new_date = date($toFormat, strtotime($date));
            } elseif ($fromFormat == "d-m-y" || $fromFormat == "d-m-Y") {
                $date_arr = explode("-", $date);
                $date_str = $date_arr[2] . "-" . $date_arr[1] . "-" . $date_arr[0];
                $new_date = date($toFormat, strtotime($date_str));
            } elseif ($fromFormat == "d/m/Y" || $fromFormat == "d/m/y") {
                $datetime_arr = explode(" ", $date);
                $date_arr = explode("/", $datetime_arr[0]);
                $date_str = $date_arr[2] . "-" . $date_arr[1] . "-" . $date_arr[0];
                $new_date = date($toFormat, strtotime($date_str));
            } elseif ($fromFormat == "d/m/Y H:i:s" || $fromFormat == "d/m/y H:i:s") {
                $datetime_arr = explode(" ", $date);
                $time = $datetime_arr[1];
                $date_arr = explode("/", $datetime_arr[0]);
                $date_str = $date_arr[2] . "-" . $date_arr[1] . "-" . $date_arr[0];
                $new_date = date($toFormat, strtotime($date_str . " " . $time));
            } elseif ($fromFormat == "d/m/Y H:i A" || $fromFormat == "d/m/y H:i A") {
                $datetime_arr = explode(" ", $date);
                $time = $datetime_arr[1] . " " . $datetime_arr[2];
                $date_arr = explode("/", $datetime_arr[0]);
                $date_str = $date_arr[2] . "-" . $date_arr[1] . "-" . $date_arr[0];
                $new_date = date($toFormat, strtotime($date_str . " " . $time));
            }
        } else {
            $new_date = "";
        }
        return $new_date;
    }

    public static function DateDiff($date1, $date2) {
        $date_diff = "";
        $date1 = self::DateFormat($date1, "Y-m-d");
        $date2 = self::DateFormat($date2, "Y-m-d");
        if (!empty($date1) && !empty($date2)) {
            $date1 = date_create($date1);
            $date2 = date_create($date2);
            $diff = date_diff($date1, $date2);
            $date_diff = $diff->format("%a");
        }
        return $date_diff;
    }

    public static function getStartAndEndDateOfWeek($week, $year, $format = "Y-m-d H:i:s") {
        $dateTime = new \DateTime();
        $dateTime->setISODate($year, $week);
        $result["start_date"] = $dateTime->format($format);
        $dateTime->modify("+6 days");
        $result["end_date"] = $dateTime->format($format);
        return $result;
    }

    /* Note: this function requires laravel intervention/image package */
    public static function UploadImage($file, $path, $ext = "", $width = 768, $height = 768, $is_thumb = false, $thumb_path = "", $thumb_width = 300, $thumb_height = 300, $is_medium = false, $medium_path = "", $medium_width = 300, $medium_height = 300) {

        /*ini_set('display_errors', 1);
        ini_set('display_startup_errors', 1);
        error_reporting(E_ALL);*/
        ini_set('memory_limit', -1);

        if (empty($ext)) {
            $ext = "jpg,jpeg,png,gif,webp";
        }
        if (!File::exists(public_path("storage/" . $path))) {
            File::makeDirectory(public_path("storage/" . $path), $mode = 0777, true, true);
        }
        if ($is_thumb && !empty($thumb_path) && !File::exists(public_path("storage/" . $thumb_path))) {
            File::makeDirectory(public_path("storage/" . $thumb_path), $mode = 0777, true, true);
        }
        if ($is_medium && !empty($medium_path) && !File::exists(public_path("storage/" . $medium_path))) {
            File::makeDirectory(public_path("storage/" . $medium_path), $mode = 0777, true, true);
        }
        $filePath = method_exists($file, 'getPathname') ? $file->getPathname() : $file;
        $imgData = @getimagesize($filePath);
        $img_width = isset($imgData[0]) ? $imgData[0] : $width;
        $img_height = isset($imgData[1]) ? $imgData[1] : $height;
        if ($img_width < $width) { $width = $img_width; }
        if ($img_height < $height) { $height = $img_height; }
        $result["success"] = false;
        $result["org_name"] = "";
        $result["file_name"] = "";
        if ($file) {
            $allowedExt = !empty($ext) ? explode(',', $ext) : ["jpg","jpeg","png","gif"];
            $extension = method_exists($file, 'getClientOriginalExtension') ? $file->getClientOriginalExtension() : pathinfo($filePath, PATHINFO_EXTENSION);
            $extension = strtolower($extension);
            $isUploadedFile = is_object($file) && method_exists($file, 'getClientOriginalExtension');
            $isValidExt = in_array($extension, $allowedExt);
            if ($isUploadedFile) {
                $validator = Validator::make(["file" => $file], ["file" => "mimes:" . implode(',', $allowedExt)]);
                if (!$validator->passes()) {
                    $result["errors"] = $validator->errors();
                    return $result;
                }
            } else {
                if (!$isValidExt) {
                    $result["errors"]["file"] = "Invalid image type";
                    return $result;
                }
            }
            $handle = @fopen($filePath, "rb");
            $opening_bytes = '';
            if ($handle) {
                $opening_bytes = fread($handle, min(filesize($filePath), 2048));
                fclose($handle);
            }
            if ($opening_bytes && (strlen(strpos($opening_bytes, "<?php")) > 0) && (strpos($opening_bytes, "<?php") >= 0 || strpos($opening_bytes, "<?PHP") >= 0)) {
                $result["errors"]["file"] = "Invalid image!";
            } else {
                $fileOriginalName = method_exists($file, 'getClientOriginalName') ? $file->getClientOriginalName() : basename($filePath);
                $fileOriginalName = pathinfo($fileOriginalName, PATHINFO_FILENAME);
                $fileOriginalName = self::sanitizeUploadFile($fileOriginalName).'.'.$extension;
                $fileName = date("dmyhis") . "-" . $fileOriginalName;
                $is_uploaded = Image::read($filePath)->resize($width, $height, function ($constraint) {
                    $constraint->aspectRatio();
                })->save(public_path("storage/" . $path . $fileName), 85);
                if ($is_uploaded) {
                    $result["success"] = true;
                    if ($is_thumb && !empty($thumb_path)) {
                        Image::read($filePath)->resize($thumb_width, $thumb_height, function ($constraint) {
                            $constraint->aspectRatio();
                        })->save(public_path("storage/" . $thumb_path . $fileName), 75);
                    }
                    if ($is_medium && !empty($medium_path)) {
                        Image::read($filePath)->resize($medium_width, $medium_height, function ($constraint) {
                            $constraint->aspectRatio();
                        })->save(public_path("storage/" . $medium_path . $fileName), 80);
                    }
                    $result["org_name"] = $fileOriginalName;
                    $result["file_name"] = $fileName;
                }
            }
        }
        return $result;
    }

    public static function getImageUrl($fileName, $path, $size = 'large') {
        if (empty($fileName)) return asset('assets/img/placeholder.webp');
        $baseName = basename($fileName);
        $dir = rtrim($path, '/') . '/';
        $storagePath = 'storage/' . $dir;
        if ($size == 'thumb') {
            $storagePath .= 'thumb/';
        } elseif ($size == 'medium') {
            $storagePath .= 'medium/';
        }
        if (\Illuminate\Support\Str::startsWith($fileName, 'uploads/')) {
            $uploadsDir = trim(dirname($fileName), '/') . '/';
            $uploadsPath = 'storage/' . $uploadsDir;
            if ($size == 'thumb') {
                $uploadsPath .= 'thumb/';
            } elseif ($size == 'medium') {
                $uploadsPath .= 'medium/';
            }
            if (file_exists(public_path($uploadsPath . $baseName))) {
                return asset($uploadsPath . $baseName);
            }
        }
        if (file_exists(public_path($storagePath . $baseName))) {
            return asset($storagePath . $baseName);
        }
        if ($size != 'large' && file_exists(public_path('storage/' . $dir . $baseName))) {
            return asset('storage/' . $dir . $baseName);
        }
        if (\Illuminate\Support\Str::startsWith($fileName, 'uploads/') && file_exists(public_path('storage/' . $fileName))) {
            return asset('storage/' . $fileName);
        }
        return asset('assets/img/placeholder.webp');
    }

    public static function UploadFile($file, $path, $ext = "") {
        ini_set('memory_limit', -1);
        
        if (empty($ext)) {
            $ext = "jpg,jpeg,png,gif,doc,docx,txt,pdf";
        }
        if (!File::exists(public_path("storage/" . $path))) {
            File::makeDirectory(public_path("storage/" . $path), $mode = 0777, true, true);
        }
        $path = trim($path, '/');
        if (!File::exists(storage_path('app/public/' . $path))) {
            File::makeDirectory(storage_path('app/public/' . $path), $mode = 0777, true, true);
        }
        $result["success"] = false;
        $result["org_name"] = "";
        $result["file_name"] = "";
        $result["file_path"] = "";
        if ($file) {
            $validator = Validator::make(["file" => $file], ["file" => "mimes:" . $ext]);
            if ($validator->passes()) {
                $filePath = method_exists($file, 'getPathname') ? $file->getPathname() : $file;
                $handle = @fopen($filePath, "r");
                $opening_bytes = '';
                if ($handle) {
                    $opening_bytes = fread($handle, filesize($filePath));
                    fclose($handle);
                }
                if ($opening_bytes && (strlen(strpos($opening_bytes, "<?php")) > 0) && (strpos($opening_bytes, "<?php") >= 0 || strpos($opening_bytes, "<?PHP") >= 0)) {
                    $result["errors"]["file"] = "Invalid file!";
                } else {
                    $extension = method_exists($file, 'getClientOriginalExtension') ? $file->getClientOriginalExtension() : pathinfo($filePath, PATHINFO_EXTENSION);
                    $originalName = method_exists($file, 'getClientOriginalName') ? $file->getClientOriginalName() : basename($filePath);
                    $baseName = pathinfo($originalName, PATHINFO_FILENAME);
                    $safeName = self::sanitizeUploadFile($baseName . '.' . $extension);
                    $fileName = date("dmyhis") . "-" . $safeName;
                    $storedPath = $file->storeAs($path, $fileName, 'public');
                    if ($storedPath) {
                        $result["success"] = true;
                        $result["org_name"] = $originalName;
                        $result["file_name"] = $fileName;
                        $result["file_path"] = $storedPath; // relative to public disk, e.g., ck/filename
                    }
                }
            } else {
                $result["errors"] = $validator->errors();
            }
        }
        return $result;
    }

    public static function getSetting($key)
    {
        if (empty($key)) return "";

        $settings = Cache::remember("website_setting_{$key}", 3600, function () use ($key) {
            return Setting::where("key", $key)->first();
        });

        return $settings->value ?? '';
    }

    public static function getSettings(array $keyArr = [])
    {
        $allSettings = Cache::remember('website_settings_all', 3600, function () {
            return Setting::all();
        });

        if (!empty($keyArr)) {
            return $allSettings->whereIn('key', $keyArr)->pluck('value', 'key')->toArray();
        }

        return $allSettings->pluck('value', 'key')->toArray();
    }


    public static function GetCountry($id = 0, $col_name = "") {
        $value = "";
        if (is_numeric($id) && $id > 0) {
            $country = DB::table("countries")->where("id", $id)->first();
            if (!empty($col_name) && isset($country->{$col_name})) {
                $value = $country->{$col_name};
            } else {
                $value = $country;
            }
        }
        return $value;
    }

    public static function GetParentCategory($category) {
        $parent = "";
        if (isset($category->parent) && count($category->parent) > 0) {
            $parent = $category->parent;
        }
        return $parent;
    }

    public static function GetParentCategories($id = "", $type = "", $params = []) {
        $categories = "";
        $orderBy = isset($params["orderBy"]) && ($params["orderBy"] == "desc" || $params["orderBy"] == "asc") ? $params["orderBy"] : "asc";
        $order_type = isset($params["order_type"]) && ($params["order_type"] == "desc" || $params["order_type"] == "asc") ? $params["order_type"] : "asc";
        $category_query = Category::where("status", 1);
        if ($type == "design") {
            $category_query->where("parent_id", 0);
        }
        if (!empty($type)) {
            $category_query->where("type", $type);
        }
        if (isset($params["orderBy"]) && !empty($params["orderBy"])) {
            $category_query->orderBy($params["orderBy"], $order_type);
        }
        if (isset($params["limit"]) && is_numeric($params["limit"]) && $params["limit"] > 0) {
            $category_query->limit($params["limit"]);
        }
        if (is_numeric($id) && $id > 0) {
            $category_query->where("id", $id);
            $categories = $category_query->first();
        } else {
            $categories = $category_query->get();
        }
        return $categories;
    }

    public static function getCategories($id = "", $parent_id = 0, $params = []) {
        $categories = "";
        $category_query = Category::where("status", 1);
        $category_query->where("parent_id", $parent_id);
        if (!empty($id)) {
            //$category_query->where('id', $id);
            $category_query->where(function ($query) use ($id) {
                $query->where("id", $id)->orWhere("slug", $id);
            });
            $categories = $category_query->first();
        } else {
            $categories = $category_query->orderBy("sort_order", "asc")->get();
        }
        return $categories;
    }

    public static function CategoriesMenu($type = "", $className = "", $idName = "") {
        $CatParams = [];
        $CatParams["orderBy"] = "sort_order";
        $CatParams["order_type"] = "asc";
        $ParentCategories = self::GetParentCategories("", $type, $CatParams);
        //pr($ParentCategories); die;
        $all_menu = url("designs");
        $menu_list = "";
        $menu_list.= '<ul class="' . $className . '" id="' . $idName . '">';
        $menu_list.= '<li><a href="' . $all_menu . '">All Designs</a></li>';
        $menu_list.= '<li><a href="#">All Best Sellers</a></li>';
        if (!empty($ParentCategories) && count($ParentCategories)) {
            foreach ($ParentCategories as $parentCat) {
                $childrenCat = $parentCat->children;
                $cat_url = url("designs?cat=" . $parentCat->slug);
                if (isset($childrenCat) && count($childrenCat) > 0) {
                    $cat_url = "javascript:void(0)";
                }
                $menu_list.= '<li><a href="' . $cat_url . '">' . $parentCat->name . "</a>";
                if (isset($childrenCat) && count($childrenCat) > 0) {
                    $childrenCat = $childrenCat->sortBy("sort_order");
                    $menu_list.= self::CategoriesMenuChild($childrenCat, $className, $idName);
                }
                $menu_list.= "</li>";
            }
        }
        $menu_list.= "</ul>";
        return $menu_list;
    }

    public static function CategoriesMenuChild($childCategories, $className = "", $idName = "") {
        $menu_list_child = "";
        if (!empty($childCategories) && count($childCategories) > 0) {
            $menu_list_child.= '<ul class="' . $className . '" id="' . $idName . '">';
            foreach ($childCategories as $childCat) {
                $childrenCat = $childCat->children;
                $cat_url = url("designs?cat=" . $childCat->slug);
                if (isset($childrenCat) && count($childrenCat) > 0) {
                    $cat_url = "javascript:void(0)";
                }
                $menu_list_child.= '<li><a href="' . $cat_url . '">' . $childCat->name . "</a>";
                if (isset($childrenCat) && count($childrenCat) > 0) {
                    $childrenCat = $childrenCat->sortBy("sort_order");
                    $menu_list_child.= self::CategoriesMenuChild($childrenCat, $className, $idName);
                }
                $menu_list_child.= "</li>";
            }
            $menu_list_child.= "</ul>";
        }
        return $menu_list_child;
    }

    private static $parentCatArr = [];

    public static function categoryParentForBreadcrumb($category) {
        if (isset($category->parent) && count($category->parent) > 0) {
            $parent_category = $category->parent;
            self::$parentCatArr[] = $parent_category->toArray();
            if (isset($parent_category->parent) && count($parent_category->parent) > 0) {
                self::categoryParentForBreadcrumb($parent_category);
            }
        }
    }

    public static function CategoryBreadcrumb($category, $first_uri, $first_uri_name, $is_last_link = false) {
        self::$parentCatArr = [];
        $BackUrl = self::BackUrl();
        //prd($category->toArray());
        $breadcrumb = "";
        if (!empty($first_uri_name)) {
            $breadcrumb.= '<a href="' . url($first_uri) . '" class="btn-link" >' . $first_uri_name . "</a>";
        }
        $hierarchy_arr = [];
        if (!empty($category) && count($category) > 0) {
            self::categoryParentForBreadcrumb($category);
            $hierarchy_arr = self::$parentCatArr;
            $hierarchy_arr_rev = array_reverse($hierarchy_arr);
            //prd($hierarchy_arr_rev);
            if (!empty($hierarchy_arr_rev) && count($hierarchy_arr_rev) > 0) {
                foreach ($hierarchy_arr_rev as $cat) {
                    $cat = (object)$cat;
                    if (isset($cat->name)) {
                        if (!empty($first_uri_name)) {
                            $breadcrumb.= '&nbsp;<i aria-hidden="true" class="fa fa-angle-double-right"></i>&nbsp;';
                        }
                        $breadcrumb.= '<a href="' . url($first_uri . "&parent_id=" . $cat->id) . '" class="btn-link" >' . $cat->name . "</a>";
                        $breadcrumb.= '&nbsp;<i aria-hidden="true" class="fa fa-angle-double-right"></i>&nbsp;';
                    }
                }
                //$breadcrumb .= '&nbsp;<i aria-hidden="true" class="fa fa-angle-double-right"></i>&nbsp;';
                
            } elseif (!empty($first_uri_name)) {
                $breadcrumb.= '&nbsp;<i aria-hidden="true" class="fa fa-angle-double-right"></i>&nbsp;';
            }
            if ($is_last_link) {
                $breadcrumb.= '<a href="' . url("admin/categories?parent_id=" . $category->id . "&back_url=" . $BackUrl) . '">' . $category->name . "</a>";
            } else {
                $breadcrumb.= '<a href="javascript:void(0)">' . $category->name . "</a>";
            }
        }
        return $breadcrumb;
    }

    public static function CategoryBreadcrumbFrontend($category, $first_uri, $first_uri_name, $is_last_link = false) {
        self::$parentCatArr = [];
        //prd($category->toArray());
        $breadcrumb = "";
        if (!empty($first_uri_name)) {
            $breadcrumb.= '<a href="' . url($first_uri) . '" >' . $first_uri_name . "</a>";
        }
        $hierarchy_arr = [];
        if (!empty($category) && count($category) > 0) {
            $category_id = isset($category->pivot->id) ? $category->pivot->id : 0;
            $p1_cat = isset($category->pivot->p1_cat) ? $category->pivot->p1_cat : 0;
            $p2_cat = isset($category->pivot->p2_cat) ? $category->pivot->p2_cat : 0;
            self::categoryParentForBreadcrumb($category);
            $hierarchy_arr = self::$parentCatArr;
            $hierarchy_arr_rev = array_reverse($hierarchy_arr);
            //prd($hierarchy_arr_rev);
            $pcat = "";
            if (!empty($hierarchy_arr_rev) && count($hierarchy_arr_rev) > 0) {
                foreach ($hierarchy_arr_rev as $cat) {
                    $cat = (object)$cat;
                    if (isset($cat->name)) {
                        if (!empty($first_uri_name)) {
                            $breadcrumb.= '&nbsp;<i aria-hidden="true" class="fa fa-angle-double-right"></i>&nbsp;';
                        }
                        $pCatUrl = route("products.list", ["pcat" => $cat->slug, ]);
                        if ($cat->id == $p1_cat) {
                            $pcat = $cat->slug;
                            $pCatUrl = route("products.list", ["pcat" => $cat->slug, ]);
                        } elseif ($cat->id == $p2_cat) {
                            //$pCatUrl = 'javascript:void(0)';
                            $pCatUrl = route("products.list", ["pcat" => $pcat, "p2cat" => $cat->slug, ]);
                        }
                        $breadcrumb.= '<a href="' . $pCatUrl . '" >' . $cat->name . "</a>";
                        $breadcrumb.= '&nbsp;<i aria-hidden="true" class="fa fa-angle-double-right"></i>&nbsp;';
                    }
                }
                //$breadcrumb .= '&nbsp;<i aria-hidden="true" class="fa fa-angle-double-right"></i>&nbsp;';
                
            } elseif (!empty($first_uri_name)) {
                $breadcrumb.= '&nbsp;<i aria-hidden="true" class="fa fa-angle-double-right"></i>&nbsp;';
            }
            if ($is_last_link) {
                $catUrl = route("products.list", ["pcat" => $pcat, "cat[]" => $category->slug, ]);
                $breadcrumb.= '<a href="' . $catUrl . '">' . $category->name . "</a>";
            } else {
                //$breadcrumb .= '<a href="javascript:void(0)">'.$category->name.'</a>';
                $breadcrumb.= $category->name;
            }
        }
        return $breadcrumb;
    }

    public static function categoryDropDown($dropdown_name, $classAttr = "", $idAtrr = "", $selected_value = "", $allow_multiple = false) {
        $dropdown = '<select name="' . $dropdown_name . '" class="' . $classAttr . '" id="' . $idAtrr . '" >';
        if ($allow_multiple) {
            $dropdown = '<select name="' . $dropdown_name . '[]" class="' . $classAttr . '" id="' . $idAtrr . '" multiple>';
        }
        $dropdown .= '<option value="">--Select--</option>';
        $categories = Category::where(["parent_id" => 0])->orderBy("name")->get();
        if (!empty($categories) && count($categories) > 0) {
            foreach ($categories as $category) {
                $dropdown .= self::makeCategoryDropDown($category, $selected_value);
            }
        }
        $dropdown .= "</select>";
        return $dropdown;
    }

    public static function makeCategoryDropDown($category, $selected_value = "") {
        $selected = "";
        if (is_array($selected_value)) {
            if (in_array($category->id, $selected_value)) {
                $selected = "selected";
            }
        } else {
            if ($category->id == $selected_value) {
                $selected = "selected";
            }
        }
        $category_name = $category->name;
        if (isset($category->parent) && count($category->parent) > 0) {
            $mark = self::markCategoryParent($category);
            $category_name = $mark . $category_name;
        }
        $options = '<option value="' . $category->id . '" ' . $selected . " >" . $category_name . "</option>";
        if (isset($category->children) && count($category->children) > 0) {
            foreach ($category->children as $child_cat) {
                $options.= self::makeCategoryDropDown($child_cat, $selected_value);
            }
        }
        return $options;
    }

    public static function markCategoryParent($category) {
        $mark = "";
        if (isset($category->parent) && count($category->parent) > 0) {
            $mark.= " - ";
            $category_parent = $category->parent;
            $mark.= self::markCategoryParent($category_parent);
        }
        return $mark;
    }

    public static function getMenu($slug = "top-menu", $parent = 0) {
        $result = "";
        if (!empty($slug)) {
            $result = Menu::where(["slug" => $slug, "status" => 1])->first();
        }
        return $result;
    }

    public static function getMenuItemsList($menuItems, $menu_id, $is_parent = true, $parent_class = "", $child_class = "")
    {
        $routeName = self::getAdminRouteName();
        $list = "";

        if ($is_parent) {
            $list .= '<ol class="' . $parent_class . ' list-unstyled">';
        }

        if (!empty($menuItems) && $menuItems->count() > 0) {
            foreach ($menuItems as $mi) {
                $item_url = route($routeName . ".menus.items", CustomHelper::encrypt($menu_id) . "/" . CustomHelper::encrypt($mi->id));
                
                // Get link type icon
                $linkTypeIcon = self::getLinkTypeIcon($mi->link_type);
                
                // Get status badge
                $statusBadge = $mi->status == 1 
                    ? '<span class="badge bg-success me-2">Active</span>' 
                    : '<span class="badge bg-danger me-2">Inactive</span>';

                $list .= '<li class="' . $child_class . '" id="item_id_' . $mi->id . '" data-item-id="' . $mi->id . '">';
                $list .= '<div class="menu-item-content">';
                
                // Drag handle
                $list .= '<div class="menu-item-drag handle">';
                $list .= '<i class="ti tabler-grip-vertical"></i>';
                $list .= '</div>';
                
                // Menu item details
                $list .= '<div class="menu-item-details">';
                $list .= '<div class="menu-item-icon">';
                $list .= '<i class="' . $linkTypeIcon . '"></i>';
                $list .= '</div>';
                $list .= '<div class="menu-item-text">';
                $list .= '<div class="menu-item-name">' . htmlspecialchars($mi->title) . '</div>';
                $list .= '<div class="menu-item-url">' . htmlspecialchars($mi->url ?: 'No URL set') . '</div>';
                $list .= '</div>';
                $list .= '</div>';
                
                // Actions
                $list .= '<div class="menu-item-actions">';
                $list .= $statusBadge;
                
                // Edit permission check
                if (auth()->user()->hasRole('SuperAdmin') || (auth()->user()->can('menus.edit'))) {
                    $list .= '<a href="' . $item_url . '" class="btn-icon btn-edit" title="Edit">';
                    $list .= '<i class="ti tabler-pencil"></i>';
                    $list .= '</a>';
                }
                
                // Delete permission check
                if (auth()->user()->hasRole('SuperAdmin') || (auth()->user()->can('menus.delete'))) {
                    $list .= '<button type="button" class="btn-icon btn-delete delItem" data-id="' . $mi->id . '" title="Delete">';
                    $list .= '<i class="ti tabler-trash"></i>';
                    $list .= '</button>';
                }
                
                $list .= '</div>';
                
                $list .= '</div>';

                // Recursive Children
                if ($mi->children && $mi->children->count() > 0) {
                    $list .= '<ol class="nested-menu">';
                    $list .= self::getMenuItemsList($mi->children, $menu_id, false, $parent_class, $child_class);
                    $list .= '</ol>';
                }

                $list .= '</li>';
            }
        }

        if ($is_parent) {
            $list .= '</ol>';
        }

        return $list;
    }

    /**
     * Get icon for link type
     */
    public static function getLinkTypeIcon($linkType)
    {
        switch ($linkType) {
            case 'cms':
                return 'ti tabler-file-text';
            case 'blog':
                return 'ti tabler-article';
            case 'news':
                return 'ti tabler-news';
            case 'event':
                return 'ti tabler-calendar-event';
            case 'category':
                return 'ti tabler-category';
            case 'internal':
                return 'ti tabler-link';
            case 'external':
                return 'ti tabler-external-link';
            case 'custom':
                return 'ti tabler-world';
            default:
                return 'ti tabler-link';
        }
    }

    public static function getMenuForFront($menuItems, $is_parent = true, $parent_class = "", $child_class = "", $child_parent_class = "", $have_child_class = "", $anchor_class = "") {
        $routeName = self::getAdminRouteName();
        $list = "";
        if ($is_parent) {
            $list.= '<ul class="' . $parent_class . '">';
        }
        if (!empty($menuItems) && $menuItems->count() > 0) {
            foreach ($menuItems as $mi) {
                $menuUrl = url($mi->url);
                $target = $mi->target;
                if ($mi->link_type == "external" && !empty($mi->url)) {
                    $menuUrl = $mi->url;
                }
                if(!empty($have_child_class) && $mi->children->count() > 0){
                    $list.= '<li class="' . $child_class.' '. $have_child_class . '" id="item_id_' . $mi->id . '">';
                }else{
                    $list.= '<li class="' . $child_class . '" id="item_id_' . $mi->id . '">';
                }
                $list.= '<a class="' . $anchor_class . '" href="' . $menuUrl . '" target="' . $target . '">';
                $list.= $mi->title;
                $list.= "</a>";
                if (isset($mi->children) && $mi->children->count() > 0) {
                    $list.= '<ul class="' . $child_parent_class . '">';
                    $list.= self::getMenuForFront($mi->children, false, $parent_class, $child_class);
                    $list.= "</ul>";
                }
                $list.= "</li>";
            }
        }
        if ($is_parent) {
            $list.= "</ul>";
        }
        return $list;
    }

    public static function getNameFromNumber($num) {
        $index = 0;
        $index = abs($index * 1);
        $numeric = ($num - $index) % 26;
        $letter = chr(65 + $numeric);
        $num2 = intval(($num - $index) / 26);
        if ($num2 > 0) {
            return self::getNameFromNumber($num2 - 1 + $index) . $letter;
        } else {
            return $letter;
        }
    }

    public static function BackUrl() {
        $uri = request()->path();
        if (count(request()->input()) > 0) {
            $request_input = request()->input();
            if (isset($request_input["back_url"])) {
                unset($request_input["back_url"]);
            }
            $uri.= "?" . http_build_query($request_input, "", "&");
        }
        //rawurlencode(str)
        //return rawurlencode($uri);
        return $uri;
    }

    public static function sendEmail($viewPath, $viewData, $to, $from, $replyTo, $subject, $params = []) {
        try {
            Mail::send($viewPath, $viewData, function ($message) use ($to, $from, $replyTo, $subject, $params) {
                $attachment = isset($params["attachment"]) ? $params["attachment"] : "";
                if (!empty($replyTo)) {
                    $message->replyTo($replyTo);
                }
                if (!empty($from)) {
                    $message->from($from);
                }
                if (!empty($attachment)) {
                    $message->attach($attachment);
                }
                $message->to($to);
                $message->subject($subject);
            });
        }
        catch(\Exception $e) {
            // Never reached
            
        }
        // if (count(Mail::failures()) > 0) {
        //     return false;
        // } else {
        return true;
        //}
        
    }

    public static function sendEmailRaw($html, $plainText, $to, $from, $replyTo, $subject, $params = []) {
        try {
            Mail::raw([], function ($message) use ($html, $plainText, $to, $from, $replyTo, $subject, $params) {
                $attachment = isset($params["attachment"]) ? $params["attachment"] : "";
                if (!empty($replyTo)) {
                    $message->replyTo($replyTo);
                }
                if (!empty($from)) {
                    $message->from($from);
                }
                if (!empty($attachment)) {
                    $message->attach($attachment);
                }
                $message->setBody($html, "text/html");
                $message->addPart($plainText, "text/plain");
                $message->to($to);
                $message->subject($subject);
            });
        }
        catch(\Exception $e) {
            // Never reached
            
        }
        if (count(Mail::failures()) > 0) {
            return false;
        } else {
            return true;
        }
    }

    public static function getCMSPage($name, $cols = ["*"]) {
        //prd($name);
        $data = [];
        $data["title"] = "";
        $data["heading"] = "";
        $data["content"] = "";
        $data["meta_title"] = "";
        $data["meta_keyword"] = "";
        $data["meta_description"] = "";
        $data["status"] = 0;
        if (!empty($name)) {
            $cms_data = CmsPages::where("slug", $name)->select($cols)->first();
            if (!empty($cms_data)) {
                $title = isset($cms_data->title) ? $cms_data->title : "";
                $id = isset($cms_data->id) ? $cms_data->id : "";
                $parent_id = isset($cms_data->parent_id) ? $cms_data->parent_id : "";
                $heading = isset($cms_data->heading) ? $cms_data->heading : "";
                $brief = isset($cms_data->brief) ? $cms_data->brief : "";
                $content = isset($cms_data->content) ? $cms_data->content : "";
                $template = isset($cms_data->template) ? $cms_data->template : "";
                $image = isset($cms_data->image) ? $cms_data->image : "";
                $banner_image = isset($cms_data->banner_image) ? $cms_data->banner_image : "";
                $meta_title = isset($cms_data->meta_title) ? $cms_data->meta_title : "";
                $meta_keyword = isset($cms_data->meta_keyword) ? $cms_data->meta_keyword : "";
                $meta_description = isset($cms_data->meta_description) ? $cms_data->meta_description : "";
                $status = isset($cms_data->status) ? $cms_data->status : "";
                $data["title"] = $title;
                $data["id"] = $id;
                $data["parent_id"] = $parent_id;
                $data["heading"] = $heading;
                $data["brief"] = $brief;
                $data["template"] = $template;
                $data["image"] = $image;
                $data["banner_image"] = $banner_image;
                $data["content"] = $content;
                $data["meta_title"] = $meta_title;
                $data["meta_keyword"] = $meta_keyword;
                $data["meta_description"] = $meta_description;
                $data["cms"] = $cms_data;
                $data["status"] = $status;
            }
        }
        return $data;
    }

    public static function updateData($tbl, $id_col, $id, $data) {
        $is_updated = 0;
        if (!empty($tbl) && !empty($id_col) && is_numeric($id) && $id > 0 && is_array($data) && count($data) > 0) {
            $is_updated = DB::table($tbl)->where($id_col, $id)->update($data);
        }
        return $is_updated;
    }

    public static function isSerialized($value, &$result = null) {
        if (empty($value)) {
            return false;
        }
        // Bit of a give away this one
        if (!is_string($value)) {
            return false;
        }
        // Serialized false, return true. unserialize() returns false on an
        // invalid string or it could return false if the string is serialized
        // false, eliminate that possibility.
        if ($value === "b:0;") {
            $result = false;
            return true;
        }
        $length = strlen($value);
        $end = "";
        switch ($value[0]) {
            case "s":
                if ($value[$length - 2] !== '"') {
                    return false;
                }
            case "b":
            case "i":
            case "d":
                // This looks odd but it is quicker than isset()ing
                $end.= ";";
            case "a":
            case "O":
                $end.= "}";
                if ($value[1] !== ":") {
                    return false;
                }
                switch ($value[2]) {
                    case 0:
                    case 1:
                    case 2:
                    case 3:
                    case 4:
                    case 5:
                    case 6:
                    case 7:
                    case 8:
                    case 9:
                    break;
                    default:
                        return false;
                }
            case "N":
                $end.= ";";
                if ($value[$length - 1] !== $end[0]) {
                    return false;
                }
            break;
            default:
                return false;
        }
        if (($result = @unserialize($value)) === false) {
            $result = null;
            return false;
        }
        return true;
    }

    public static function makeStarRatingArr($rating = 5) {
        $ratingArr = explode(".", $rating);
        $count = $ratingArr[0];
        $revCount = 5 - $count;
        $starColorArr = [];
        for ($i = 1;$i <= $count;$i++) {
            $starColorArr[] = '<span class="fa fa-star color"></span>';
        }
        $starArr = [];
        if ($revCount > 0) {
            for ($r = 1;$r <= $revCount;$r++) {
                $starArr[] = '<span class="fa fa-star"></span>';
            }
        }
        $starArray = array_merge($starColorArr, $starArr);
        return $starArray;
    }

    public static function wordsLimit($str, $limit = 150, $isStripTags = false, $allowTags = "") {
        $newStr = "";
        if (strlen($str) <= $limit) {
            $newStr = $str;
        } else {
            $newStr = substr($str, 0, $limit) . " ...";
        }
        if ($isStripTags) {
            if (!empty($allowTags)) {
                $newStr = strip_tags($newStr, $allowTags);
            } else {
                $newStr = strip_tags($newStr);
            }
        }
        return $newStr;
    }
    
    public static function convertCurrency($amount, $from = "INR", $to = "USD", $decimals = 0) {
        $CurrencyConverter = new CurrencyConverter();
        $converted = $CurrencyConverter->convert($amount, $from, $to, $decimals);
        return $converted;
    }
    
    public static function isMobile($userAgent = null, $httpHeaders = null) {
        $detect = new MobileDetect();
        $detected = $detect->isMobile($userAgent = null, $httpHeaders = null);
        return $detected;
    }

    private static $categoryAttributes = [];

    public static function getParentCategoryAttributes($category) {
        if (!empty($category) && count($category) > 0) {
            if (isset($category->parent) && count($category->parent) > 0) {
                self::getParentCategoryAttributes($category->parent);
            }
            $attributes = isset($category->categoryAttributes) ? $category->categoryAttributes : "";
            if (!empty($attributes) && count($attributes) > 0) {
                self::$categoryAttributes[] = $attributes;
            }
        }
        return self::$categoryAttributes;
    }

    public static function getData($tbl, $id = 0, $where = "", $selectArr = ["*"], $params = []) {
        $result = "";
        $orderByArr = isset($params["orderBy"]) ? $params["orderBy"] : "";
        $featured = isset($params["featured"]) ? $params["featured"] : "0";
        $query = DB::table($tbl);
        $query->select($selectArr);
        if (!empty($where) && count($where) > 0) {
            $query->where($where);
        }
        if (!empty($orderByArr) && count($orderByArr) > 0) {
            foreach ($orderByArr as $orderKey => $orderVal) {
                $query->orderBy($orderKey, $orderVal);
            }
        }
        if (isset($featured) && !empty($featured)) {
            $query->where("featured", $featured);
        }
        if (isset($params["limit"]) && is_numeric($params["limit"]) && $params["limit"] > 0) {
            $query->limit($params["limit"]);
        }
        if (is_numeric($id) && $id > 0) {
            $query->where("id", $id);
            $result = $query->first();
        } else {
            $result = $query->get();
        }
        return $result;
    }

    // Common Function for GetEvents
    public static function getEvents($id = "", $limit = "", $params = []) {
        $events = "";
        //$params['orderBy'] = ['id'=>'asc', 'name'=>'desc'];
        $orderByArr = isset($params["orderBy"]) ? $params["orderBy"] : "";
        $featured = isset($params["featured"]) ? $params["featured"] : "0";
        $event_query = Event::where("status", 1);
        if (!empty($orderByArr) && count($orderByArr) > 0) {
            foreach ($orderByArr as $orderKey => $orderVal) {
                $event_query->orderBy($orderKey, $orderVal);
            }
        }
        if (isset($featured) && !empty($featured)) {
            $event_query->where("featured", $featured);
        }
        if (isset($params["limit"]) && is_numeric($params["limit"]) && $params["limit"] > 0) {
            $event_query->limit($params["limit"]);
        }
        if (is_numeric($id) && $id > 0) {
            $event_query->where("id", $id);
            $events = $event_query->first();
        } else {
            $events = $event_query->get();
        }
        return $events;
    }

    public static function getBlogs($id = "", $type = "blogs", $limit = "", $params = []) {
        $data = "";
        $blog_type_arr = config("custom.blog_type_arr");
        $type = isset($blog_type_arr[$type]) ? $type : "blogs";
        //$params['orderBy'] = ['id'=>'asc', 'name'=>'desc'];
        $orderByArr = isset($params["orderBy"]) ? $params["orderBy"] : "";
        $featured = isset($params["featured"]) ? $params["featured"] : "0";
        $news_query = Blog::where(["status" => 1, "type" => $type]);
        if (!empty($orderByArr) && count($orderByArr) > 0) {
            foreach ($orderByArr as $orderKey => $orderVal) {
                $news_query->orderBy($orderKey, $orderVal);
            }
        }
        if (isset($featured) && !empty($featured)) {
            $news_query->where("featured", $featured);
        }
        if (isset($params["limit"]) && is_numeric($params["limit"]) && $params["limit"] > 0) {
            $news_query->limit($params["limit"]);
        }
        if (is_numeric($id) && $id > 0) {
            $news_query->where("id", $id);
            $data = $news_query->first();
        } else {
            $data = $news_query->get();
        }
        return $data;
    }

    public static function getCmsData($id = 0, $parent_id = 0, $limit = "", $params = []) {
        $data = "";
        $parent_id = isset($parent_id) ? $parent_id : 0;
        $featured = isset($params["featured"]) ? $params["featured"] : "0";
        $query = CmsPages::where("status", 1);
        if (is_numeric($parent_id) && $parent_id > 0) {
            $query->where("parent_id", $parent_id);
        }
        if (isset($featured) && !empty($featured)) {
            $query->where("featured", $featured);
        }
        if (isset($params["limit"]) && is_numeric($params["limit"]) && $params["limit"] > 0) {
            $query->limit($params["limit"]);
        }
        if (is_numeric($id) && $id > 0) {
            $query->where("id", $id);
            $data = $query->first();
        } else {
            $data = $query->get();
        }
        return $data;
    }

    /* End Common Function */
    // For Menus
    public static function getHeaderMenu($menu_name = "", $menu_id = "", $parent_id = 0, $ul_class = "", $child_ul_class = "", $li_class = "", $child_li_class = "") {
        $mess = "";
        $id = 0;
        if ($menu_name != "") {
            $menu = Menu::where(["slug" => $menu_name])->first();
            if (!empty($menu)) {
                $id = $menu->id;
            }
        }
        $query = MenuItem::where("menu_id", $id)->orderBy("sort_order", "asc");
        if (!empty($menu_id)) {
            $query->where("id", $menu_id);
        }
        if (!empty($parent_id)) {
            $query->where("parent_id", $parent_id);
        }
        $itemData = $query->get();
        $res = $itemData;
        //prd($itemData);
        $total_menu = count($itemData);
        $menu_count = 2;
        if (!empty($res)) {
            $mess.= '<ul class="' . $ul_class . '">';
            foreach ($res as $r) {
                $url = "";
                if (!empty($r->slug_url)) {
                    $url = url($r->slug_url);
                }
                if (empty($url)) {
                    $url = "javascript:void(0)";
                    if ($r->url == "/") {
                        $url = url("");
                    }
                    if ($r->link_type == "external" && !empty($r->url)) {
                        $url = $r->url;
                    }
                    if ($r->link_type == "internal" && !empty($r->url)) {
                        $url = url("/") . $r->url;
                    }
                }
                $name = $r->title;
                $target = $r->target;
                $mess.= "<li class=" . $li_class . "><a target=" . $target . " href=" . $url . ">" . $name . "</a>";
                $mess.= self::getHeaderMenu($menu_name = "", $r->menu_id, $r->id, $child_ul_class, "", $child_li_class, "");
                $mess.= "</li>";
                if ($r->parent_id == 0) {
                    $menu_count++;
                }
            }
            $mess.= "</ul>";
        }
        return $mess;
    }

    public static function getStaticFormElements() {
        $result = [];
        $formElements = FormElement::where("is_static", 1)->get();
        return $formElements;
    }

    public static function sanitizeUploadFile($filename) {
        $imgName = $filename;
        $indexOFF = strrpos($imgName, ".");
        $nameFile = substr($imgName, 0, $indexOFF);
        $extension = substr($imgName, $indexOFF);
        $clean = preg_replace("([^\w\s\d\-_~,;\[\]\(\)])", "", $nameFile);
        $NAMEFILE = str_replace(" ", "", $clean) . $extension;
        if (strlen($NAMEFILE) > 50) {
            $NAMEFILE = substr($NAMEFILE, 0, 50);
        }
        return $NAMEFILE;
    }

    // Add Activity Log Code Start....
    public static function recordActionLog($function_name = "", $action_table = "", $row_id = "", $action_type = "", $action_description = "", $description = "", $user_id = "") {
        $isSaved = "";
        $insertData = [];
        $user = auth()->user();
        if (!empty($function_name)) {
            $insertData["function_name"] = $function_name;
        }
        if (!empty($action_table)) {
            $insertData["action_table"] = $action_table;
        }
        $insertData["row_id"] = is_numeric($row_id) ? (int)$row_id : 0;
        if (!empty($action_type)) {
            $insertData["action_type"] = $action_type;
        }
        if (!empty($action_description)) {
            $insertData["action_description"] = $action_description;
        }
        if (!empty($description)) {
            $insertData["description"] = $description;
        }
        $insertData["user_id"] = $user->id;
        $insertData["ip_address"] = request()->ip();
        $isSaved = DB::table("activity_logs")->insert($insertData);
        return $isSaved;
    }
    // Add Activity Log Code Closed....

    // get Widget Code Start....
    public static function getWidget($widgetID) {
        if (!empty($widgetID) && is_numeric($widgetID)) {
            $widgetDetail = Widget::where('id', $widgetID)->where('status', 1)->first();
            return $widgetDetail;
        } else {
            $widgetDetail = Widget::where('slug', $widgetID)->where('status', 1)->first();
            return $widgetDetail;
        }
        return false;
    }
    // get Widget Code Closed....

    // Get Service Levels
    public static function getServiceLevels() {
        $service_level_arr = ServiceLevel::where('status',1)->pluck('name','id')->toArray();
        return $service_level_arr;
    }
    /* End of helper class */

    public static function encrypt($id) {
        return Crypt::encrypt($id);
    }

    public static function decrypt($encryptedId) {
        return Crypt::decrypt($encryptedId);
    }

    /**
     * Get validation rules for custom fields by module.
     *
     * @param string $module
     * @return array
     */
    public static function getCustomFieldRules(string $module,int $id = 0): array
    {
        $rules = [];
        $attributes = [];

        $customFields = CustomField::where('module', 'cms')->where(function ($query) use ($id) {
            $query->where('ref_id', 0)
            ->orWhere('ref_id', $id);
        })->get();

        foreach ($customFields as $field) {
            $rulesList = [];

            $validationJson = json_decode($field->validation ?? '{}', true);
            $fileConstraints = json_decode($field->file_constraints ?? '{}', true);

            // Required or Nullable
            $rulesList[] = !empty($validationJson['required']) ? 'required' : 'nullable';

            // Field type based rules
            $rulesList[] = match ($field->field_type) {
                'number' => 'numeric',
                'email' => 'email',
                'date' => 'date',
                'file', 'image' => $field->field_type,
                default => '',
            };

            // Other validation rules
            foreach ($validationJson as $key => $value) {
                if ($key === 'required') continue;

                switch ($key) {
                    case 'max':
                    case 'min':
                    case 'size':
                    case 'digits':
                        $rulesList[] = "$key:$value";
                        break;

                    case 'between':
                    case 'digits_between':
                        $rulesList[] = "$key:" . implode(',', (array) $value);
                        break;

                    case 'regex':
                        // Ensure regex is wrapped properly
                        if (is_string($value) && preg_match('/^\/.*\/[a-z]*$/i', $value)) {
                            $rulesList[] = "regex:$value";
                        }
                        break;

                    case 'in':
                        $rulesList[] = 'in:' . implode(',', (array) $value);
                        break;

                    default:
                        if (!is_bool($value)) {
                            $rulesList[] = "$key:$value";
                        }
                }
            }

            // File constraints
            if (in_array($field->field_type, ['file', 'image'])) {
                if (!empty($fileConstraints['max_size'])) {
                    $rulesList[] = "max:" . $fileConstraints['max_size'];
                }

                if (!empty($fileConstraints['types'])) {
                    $rulesList[] = "mimes:" . implode(',', (array) $fileConstraints['types']);
                }

                if (!empty($fileConstraints['width']) || !empty($fileConstraints['height'])) {
                    $dimensions = [];

                    if (!empty($fileConstraints['width'])) {
                        $dimensions[] = "width={$fileConstraints['width']}";
                    }

                    if (!empty($fileConstraints['height'])) {
                        $dimensions[] = "height={$fileConstraints['height']}";
                    }

                    $rulesList[] = 'dimensions:' . implode(',', $dimensions);
                }
            }

            $key = "custom_fields.{$field->key}";
            $rules[$key] = $rulesList;
            $attributes[$key] = $field->label;
        }

        return [
            'rules' => $rules,
            'attributes' => $attributes,
        ];
    }

    /**
     * Generate a unique slug for pages (or any other model).
     *
     * @param string|null $inputSlug
     * @param string $title
     * @param int|null $ignoreId
     * @return string
     */
    public static function generateSlug($slug, $title, $modelClass, $column = 'slug', $ignoreId = null)
    {
        $slug = Str::slug($slug ?: $title);
        $originalSlug = $slug;
        $i = 1;

        while ($modelClass::where($column, $slug)
            ->when($ignoreId, fn($q) => $q->where('id', '!=', $ignoreId))
            ->exists()) {
            $slug = $originalSlug . '-' . $i;
            $i++;
        }
        return $slug;
    }

    /*public static function saveCustomFields(Request $request, int $moduleId, string $moduleType): void
    {
        if ($request->has('custom_fields') && is_array($request->custom_fields)) {
            foreach ($request->custom_fields as $fieldKey => $value) {
                $customField = CustomField::where('key', $fieldKey)->first();

                if (!$customField) {
                    continue;
                }

                $fieldId = $customField->id;
                $fieldType = $customField->field_type;

                // Handle file upload
                if (
                    in_array($fieldType, ['file', 'image']) &&
                    $request->hasFile("custom_fields.$fieldKey")
                ) {
                    $file = $request->file("custom_fields.$fieldKey");
                    $filename = time() . '_' . Str::slug(pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME));
                    $extension = $file->getClientOriginalExtension();
                    $value = $file->storeAs('uploads/custom_fields', "$filename.$extension", 'public');
                }

                // Handle checkbox or array-based values
                if (in_array($fieldType, ['checkbox', 'multi_select']) && is_array($value)) {
                    $value = implode(',', $value);
                }

                // Convert any remaining arrays to JSON string as a fallback
                if (is_array($value)) {
                    $value = json_encode($value);
                }

                // Save to DB
                CustomFieldValue::updateOrCreate(
                    [
                        'custom_field_id' => $fieldId,
                        'module_type' => $moduleType,
                        'module_id' => $moduleId,
                    ],
                    [
                        'value' => $value,
                    ]
                );
            }
        }
    }*/

    public static function saveCustomFields(Request $request, int $moduleId, string $moduleType): void
    {
        if ($request->has('custom_fields') && is_array($request->custom_fields)) {
            $customFields = $request->custom_fields;

            foreach ($customFields as $fieldKey => $value) {

                if (Str::startsWith($fieldKey, 'delete_custom_field_') && $value == 1) {
                    $realKey = Str::replaceFirst('delete_custom_field_', '', $fieldKey);

                    $customField = CustomField::where('key', $realKey)->first();
                    if (!$customField) continue;

                    $existingValue = CustomFieldValue::where([
                        'custom_field_id' => $customField->id,
                        'module_type' => $moduleType,
                        'module_id' => $moduleId,
                    ])->first();

                    $existingFilePath = $existingValue->value ?? null;

                    if (!empty($existingFilePath) && Storage::disk('public')->exists($existingFilePath)) {
                        Storage::disk('public')->delete($existingFilePath);
                    }

                    CustomFieldValue::updateOrCreate(
                        [
                            'custom_field_id' => $customField->id,
                            'module_type' => $moduleType,
                            'module_id' => $moduleId,
                        ],
                        ['value' => null]
                    );

                    continue; // Skip remaining logic for this field
                }

                if (Str::startsWith($fieldKey, 'delete_custom_field_')) {
                    continue;
                }

                $customField = CustomField::where('key', $fieldKey)->first();
                if (!$customField) continue;

                $fieldId = $customField->id;
                $fieldType = $customField->type;

                $existingValue = CustomFieldValue::where([
                    'custom_field_id' => $fieldId,
                    'module_type' => $moduleType,
                    'module_id' => $moduleId,
                ])->first();

                $existingFilePath = $existingValue->value ?? null;

                if (in_array($fieldType, ['file', 'image']) && $request->hasFile("custom_fields.$fieldKey")) {
                    /*
                    // STOPPING physical deletion
                    if (!empty($existingFilePath) && Storage::disk('public')->exists($existingFilePath)) {
                        Storage::disk('public')->delete($existingFilePath);
                    }
                    */

                    $file = $request->file("custom_fields.$fieldKey");
                    $filename = time() . '_' . Str::slug(pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME));
                    $extension = $file->getClientOriginalExtension();
                    $value = $file->storeAs('uploads/custom_fields', "$filename.$extension", 'public');
                }

                if (in_array($fieldType, ['checkbox', 'multi_select']) && is_array($value)) {
                    $value = json_encode($value);
                }

                if (is_array($value)) {
                    $value = json_encode($value);
                }

                CustomFieldValue::updateOrCreate(
                    [
                        'custom_field_id' => $fieldId,
                        'module_type' => $moduleType,
                        'module_id' => $moduleId,
                    ],
                    ['value' => $value]
                );
            }
        }
    }
}
